package com.example.community.demo;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.question_id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.type
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentor_id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    private Long commentorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_time
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.modefied
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    private Long modefied;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.like_count
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_text
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    private String commentText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parent_id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.question_id
     *
     * @return the value of comment.question_id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.question_id
     *
     * @param questionId the value for comment.question_id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.type
     *
     * @return the value of comment.type
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.type
     *
     * @param type the value for comment.type
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentor_id
     *
     * @return the value of comment.commentor_id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public Long getCommentorId() {
        return commentorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentor_id
     *
     * @param commentorId the value for comment.commentor_id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public void setCommentorId(Long commentorId) {
        this.commentorId = commentorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_time
     *
     * @return the value of comment.create_time
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_time
     *
     * @param createTime the value for comment.create_time
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.modefied
     *
     * @return the value of comment.modefied
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public Long getModefied() {
        return modefied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.modefied
     *
     * @param modefied the value for comment.modefied
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public void setModefied(Long modefied) {
        this.modefied = modefied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.like_count
     *
     * @return the value of comment.like_count
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.like_count
     *
     * @param likeCount the value for comment.like_count
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_text
     *
     * @return the value of comment.comment_text
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public String getCommentText() {
        return commentText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_text
     *
     * @param commentText the value for comment.comment_text
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public void setCommentText(String commentText) {
        this.commentText = commentText == null ? null : commentText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parent_id
     *
     * @return the value of comment.parent_id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parent_id
     *
     * @param parentId the value for comment.parent_id
     *
     * @mbg.generated Tue Apr 28 17:37:05 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}