package com.example.community.demo;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.sender
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    private Long sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.comment_id
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.type
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.receiver
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    private Long receiver;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.sender
     *
     * @return the value of notice.sender
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    public Long getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.sender
     *
     * @param sender the value for notice.sender
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    public void setSender(Long sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.comment_id
     *
     * @return the value of notice.comment_id
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.comment_id
     *
     * @param commentId the value for notice.comment_id
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.type
     *
     * @return the value of notice.type
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.type
     *
     * @param type the value for notice.type
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.receiver
     *
     * @return the value of notice.receiver
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.receiver
     *
     * @param receiver the value for notice.receiver
     *
     * @mbg.generated Fri May 22 10:17:10 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }
}